name = "ECC"
uuid = "da8f3168-f3af-11e8-3bbf-539a9fd9f5f7"
keywords = ["cryptography"]
license = "GPLv3"
authors = ["roshii <admin@brane.cc>"]
description = "Elliptic Curve Cryptography"
repository = "https://gitlab.com/braneproject/ECC.jl.git"
version = "0.0.0"

[deps]
BitIntegers = "c3b6d118-76ef-56ca-8cc7-ebb389d030a1"

[compat]
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
